-- Migration: Add procver_compact_id mapping table for spatial_id generation
--
-- The spatial_id UUID encodes a 16-bit processing version compact ID.
-- This table maps base_processing_version UUIDs to sequential compact IDs.

-- Compact ID mapping for processing versions
-- Maps base_processing_version UUID to a 16-bit integer for spatial_id encoding
CREATE TABLE IF NOT EXISTS procver_compact_id (
    procver_id UUID PRIMARY KEY REFERENCES base_processing_version(id),
    compact_id SMALLINT UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

COMMENT ON TABLE procver_compact_id IS
    'Maps base_processing_version UUIDs to compact 16-bit IDs for spatial_id encoding';

-- Populate compact IDs for existing processing versions
-- New versions will get IDs automatically via IDENTITY
INSERT INTO procver_compact_id (procver_id)
SELECT id FROM base_processing_version
ON CONFLICT DO NOTHING;

-- SQL function to extract spatial grouping prefix from a spatial_id UUID
-- Returns top 48 bits of HEALPix only (position-based grouping)
--
-- UUID Layout (128 bits, big-endian):
--   high64 (bytes 0-7):  [Reserved:2][HEALPix:62]
--   low64 (bytes 8-15):  [MJD_ms:43][ProcVer:16][DataRelease:5]
--
-- Field ordering enables hierarchical filtering: position → time → procver → dr
--
-- Grouping uses top 48 bits of HEALPix only, providing ~0.05" resolution.
-- This groups all observations at the same position regardless of time/procver.
--
-- Usage:
--   SELECT * FROM diaobject WHERE spatial_group(spatial_id) = spatial_group(target_id);
--
CREATE OR REPLACE FUNCTION spatial_group(sid UUID)
RETURNS BIGINT AS $$
DECLARE
    uuid_bytes BYTEA;
    high64 BIGINT;
BEGIN
    -- Convert UUID to binary representation (16 bytes, big-endian)
    uuid_bytes := uuid_send(sid);

    -- Extract high64 (bytes 0-7, contains HEALPix)
    high64 := (get_byte(uuid_bytes, 0)::BIGINT << 56)
            | (get_byte(uuid_bytes, 1)::BIGINT << 48)
            | (get_byte(uuid_bytes, 2)::BIGINT << 40)
            | (get_byte(uuid_bytes, 3)::BIGINT << 32)
            | (get_byte(uuid_bytes, 4)::BIGINT << 24)
            | (get_byte(uuid_bytes, 5)::BIGINT << 16)
            | (get_byte(uuid_bytes, 6)::BIGINT << 8)
            | (get_byte(uuid_bytes, 7)::BIGINT);

    -- Top 48 bits of HEALPix (shift right 16)
    -- This gives ~0.05" spatial resolution for grouping
    RETURN high64 >> 16;
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;

COMMENT ON FUNCTION spatial_group(UUID) IS
    'Extract spatial grouping prefix (top 48 bits of HEALPix = 48 bits) from spatial_id UUID. '
    'Groups all observations at the same position (~0.05" resolution) regardless of time/procver.';

-- Note: The spatial_group index is created in 2026-01-12_001_add_spatial_id.sql
-- after the spatial_id column is added to diaobject.
