#!/usr/bin/env bash
# Build and install FASTDB on the single-node Arbutus K3s cluster.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
NAMESPACE="fastdb-arbutus-dev"
RELEASE_NAME="fastdb"
VALUES_FILE="$REPO_ROOT/helm/fastdb/values-arbutus-dev.yaml"
SECRETS_FILE="$REPO_ROOT/helm/fastdb/values-arbutus-secrets.yaml"
EXTERNAL_URL="${FASTDB_EXTERNAL_URL:-http://localhost:30080/}"

export DOCKER_ARCHIVE="${DOCKER_ARCHIVE:-fastdb.local}"
export DOCKER_VERSION="${DOCKER_VERSION:-test20260428}"

if [[ $EUID -eq 0 ]]; then
  echo "Error: run this script as your normal user, not with sudo." >&2
  exit 1
fi

for command_name in curl docker git helm kubectl openssl; do
  command -v "$command_name" >/dev/null || {
    echo "Error: $command_name is required." >&2
    exit 1
  }
done

docker info >/dev/null 2>&1 || {
  echo "Error: cannot access Docker as $(id -un)." >&2
  echo "Log out and back in after running setup-arbutus-k3s.sh." >&2
  exit 1
}

kubectl get node >/dev/null || {
  echo "Error: the K3s cluster is not accessible through kubectl." >&2
  exit 1
}

NODE_IP="$(
  kubectl get nodes \
    --output=jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}'
)"
if [[ -z "$NODE_IP" ]]; then
  echo "Error: could not determine the K3s node's internal IP address." >&2
  exit 1
fi
echo "K3s node address: $NODE_IP"

if [[ ! -f "$VALUES_FILE" ]]; then
  echo "Error: values file not found: $VALUES_FILE" >&2
  exit 1
fi

echo "Initializing Git submodules..."
git -C "$REPO_ROOT" submodule update --init --recursive

# Create bind-mount sources before Docker Compose sees them. If Docker creates
# a missing bind-mount source, it may be owned by root and the non-root
# makeinstall container will not be able to write to it.
mkdir -p "$REPO_ROOT/install" "$REPO_ROOT/db"
for directory in "$REPO_ROOT/install" "$REPO_ROOT/db"; do
  if [[ ! -w "$directory" || ! -x "$directory" ]]; then
    echo "Error: $(id -un) cannot write to $directory." >&2
    echo "Fix its ownership, then rerun this script:" >&2
    echo "  sudo chown -R $(id -u):$(id -g) '$directory'" >&2
    exit 1
  fi
done

if [[ ! -f "$SECRETS_FILE" ]]; then
  echo "Creating persistent development secrets in $SECRETS_FILE..."
  umask 077
  cat >"$SECRETS_FILE" <<EOF
# Generated by install-arbutus-fastdb.sh. Do not commit this file.
secrets:
  postgres:
    password: "$(openssl rand -hex 24)"
    roPassword: "$(openssl rand -hex 24)"
    replicatorPassword: "$(openssl rand -hex 24)"
  secretKey: "$(openssl rand -hex 32)"
  mongodb:
    adminUser: admin
    adminPassword: "$(openssl rand -hex 24)"
    readerUser: alertreader
    readerPassword: "$(openssl rand -hex 24)"
    writerUser: alertwriter
    writerPassword: "$(openssl rand -hex 24)"
EOF
fi

AVAILABLE_KB="$(df -Pk / | awk 'NR == 2 { print $4 }')"
if (( AVAILABLE_KB < 10 * 1024 * 1024 )); then
  echo "Warning: less than 10 GiB is available on the root filesystem." >&2
fi

cd "$REPO_ROOT"

echo "Building FASTDB container images sequentially..."
for service_name in postgres mongodb createdb webap queryrunner; do
  echo "  $service_name"
  docker compose build "$service_name"
done

echo "Building FASTDB install/ for $EXTERNAL_URL..."
USERID="$(id -u)" GROUPID="$(id -g)" \
docker compose run --rm --entrypoint "" makeinstall /bin/bash -ec "
  touch aclocal.m4 configure
  find . -name Makefile.am -exec touch {} \\;
  find . -name Makefile.in -exec touch {} \\;
  ./configure \\
    --with-installdir=/fastdb \\
    --with-smtp-server=mailhog \\
    --with-smtp-port=1025 \\
    --with-external-url=$EXTERNAL_URL
  make install
"

echo "Removing Docker build cache to free space for K3s images..."
docker builder prune --all --force

echo "Importing FASTDB images into K3s..."
for image_name in \
  "$DOCKER_ARCHIVE/fastdb-postgres:$DOCKER_VERSION" \
  "$DOCKER_ARCHIVE/fastdb-mongodb:$DOCKER_VERSION" \
  "$DOCKER_ARCHIVE/fastdb-shell:$DOCKER_VERSION" \
  "$DOCKER_ARCHIVE/fastdb-webap:$DOCKER_VERSION" \
  "$DOCKER_ARCHIVE/fastdb-query-runner:$DOCKER_VERSION"; do
  echo "  $image_name"
  docker image save "$image_name" |
    sudo k3s ctr --namespace k8s.io images import -
done

echo "Installing FASTDB with Helm..."
# A Job's pod template is immutable. Recreate it so every upgrade runs current
# database migrations without deleting the PostgreSQL PVC.
kubectl delete job createdb \
  --namespace "$NAMESPACE" \
  --ignore-not-found

if ! helm upgrade --install "$RELEASE_NAME" "$REPO_ROOT/helm/fastdb" \
  --namespace "$NAMESPACE" \
  --create-namespace \
  --values "$VALUES_FILE" \
  --values "$SECRETS_FILE" \
  --set-string "volumes.hostPaths.install=$REPO_ROOT/install" \
  --set-string "volumes.hostPaths.db=$REPO_ROOT/db" \
  --set-string "ingestion.brokerConsumer.dockerHostIp=$NODE_IP" \
  --wait \
  --wait-for-jobs \
  --timeout 10m; then
  echo "Helm installation failed. Current status:" >&2
  kubectl get pods --namespace "$NAMESPACE" >&2 || true
  kubectl logs --namespace "$NAMESPACE" job/createdb >&2 || true
  exit 1
fi

echo "Restarting services that load the host-mounted FASTDB code..."
for deployment_name in webap queryrunner shell; do
  kubectl rollout restart "deployment/$deployment_name" --namespace "$NAMESPACE"
  kubectl rollout status "deployment/$deployment_name" \
    --namespace "$NAMESPACE" \
    --timeout=180s
done

echo "Checking FASTDB WebAP..."
curl --fail --silent --show-error \
  --retry 12 \
  --retry-all-errors \
  --retry-delay 5 \
  "http://127.0.0.1:30080/" >/dev/null

echo
kubectl get pods --namespace "$NAMESPACE"
kubectl get pvc --namespace "$NAMESPACE"
df -h /
echo
echo "FASTDB is ready inside the VM at http://localhost:30080"
echo "MailHog is ready inside the VM at http://localhost:30025"
