name: Run FASTDB Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: run fastdb tests
    runs-on: ubuntu-latest
    env:
      DOCKER_ARCHIVE: images.canfar.net/candiapl
      DOCKER_VERSION: manual-20260918

    steps:
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: log into Harbor container registry
        uses: docker/login-action@v3
        with:
          registry: images.canfar.net
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: cleanup
        run: |
          # try to save HDD space on the runner by removing some unneeded stuff
          # ref: https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: run ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          src: /home/runner/work/FASTDB

      - name: pull images
        run: |
          docker compose pull kafka-server postgres mongodb mailhog queryrunner shell webap

      - name: unpack test data
        run: |
          cd tests
          tar xf elasticc2_test_data.tar.bz2

      - name: run focused all-alerts importer tests
        run: |
          docker compose run --rm \
            -e PYTEST_ADDOPTS="-vv -s -o faulthandler_timeout=300" \
            runtests services/test_all_alerts_importer.py
          docker compose down -v
